import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // General
    'view': 'View',
    'edit': 'Edit',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'save': 'Save',
    'create': 'Create',
    'search': 'Search',
    'filter': 'Filter',
    'actions': 'Actions',
    'status': 'Status',
    'details': 'Details',
    'type': 'Type',
    'date': 'Date',
    'total': 'Total',
    'contact': 'Contact',
    'description': 'Description',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'address': 'Address',
    'city': 'City',
    'country': 'Country',
    'currency': 'Currency',
    'amount': 'Amount',
    'download': 'Download',
    'upload': 'Upload',
    'complete': 'Complete',
    'incomplete': 'Incomplete',
    'required': 'Required',
    'optional': 'Optional',
    'selectOption': 'Select an option',
    'carrierCost': 'Carrier Cost',
    'saleValue': 'Sale Value',

    // Navigation
    'dashboard': 'Dashboard',
    'operations': 'Operations',
    'documents': 'Documents',
    'reports': 'Reports',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',

    // Dashboard
    'totalTrips': 'Total Trips',
    'activeDocuments': 'Active Documents',
    'monthlyRevenue': 'Monthly Revenue',
    'pendingPayments': 'Pending Payments',
    'pendingApproval': 'pending approval',
    'increase': 'increase',
    'tripVolume': 'Trip Volume',
    'recentTrips': 'Recent Trips',
    'viewAll': 'View All',
    'tripId': 'Trip ID',
    'route': 'Route',
    'driver': 'Driver',
    'value': 'Value',
    'completed': 'Completed',
    'inTransit': 'In Transit',
    'pendingDocs': 'Pending Docs',
    'scheduled': 'Scheduled',

    // Operations
    'manageOperations': 'Manage and track all transport operations',
    'searchOperations': 'Search operations...',
    'allOperations': 'All Operations',
    'newOperation': 'New Operation',
    'operationNumber': 'Operation Number',
    'operationType': 'Operation Type',
    'international': 'International',
    'national': 'National',
    'inProgress': 'In Progress',
    'pending': 'Pending',
    'startOperation': 'Start Operation',
    'completeOperation': 'Complete Operation',
    'viewDetails': 'View Details',
    'requirements': 'Requirements',
    'missingDocuments': 'Missing Documents',
    'missingInsurance': 'Missing Insurance',
    'missingServiceProvider': 'Missing Service Provider',
    'completeRequirementsFirst': 'Complete all requirements before starting',
    'cargoInsurance': 'Cargo Insurance',
    'liabilityInsurance': 'Liability Insurance',
    'assignServiceProvider': 'Assign Service Provider',
    'selectProvider': 'Select Provider',

    // Service Providers
    'serviceProviders': 'Service Providers',
    'manageServiceProviders': 'Manage service providers and their operations',
    'newServiceProvider': 'New Service Provider',
    'providerName': 'Provider Name',
    'taxId': 'Tax ID',
    'paymentTerms': 'Payment Terms',
    'paymentTermsUSD': 'Payment Terms (USD)',
    'paymentTermsCLP': 'Payment Terms (CLP)',
    'serviceProvider': 'Service Provider',
    'providerOperations': 'Provider Operations',

    // Documents
    'documentRegistry': 'Document Registry',
    'manageDocuments': 'Manage all your transport documents in one place',
    'addDocument': 'Add Document',
    'registerNewDocument': 'Register New Document',
    'documentType': 'Document Type',
    'documentDate': 'Document Date',
    'documentDescription': 'Document Description',
    'uploadDocument': 'Upload Document',
    'searchDocuments': 'Search documents...',
    'allDocuments': 'All Documents',
    'approved': 'Approved',
    'selectType': 'Select type',
    'selectOperation': 'Select operation',
    'uploadFile': 'Upload a file',
    'orDragAndDrop': 'or drag and drop',
    'uploadSuccess': 'Upload Successful',
    'documentRegistered': 'Document Registered',
    'registerDocument': 'Register Document',
    'noDocumentsFound': 'No documents found',
    'enterDescription': 'Enter document description',

    // Reports & Analytics
    'reports': 'Reports & Analytics',
    'visualizeData': 'Visualize and analyze your transportation data',
    'exportToExcel': 'Export to Excel',
    'dateRange': 'Date Range',
    'reportType': 'Report Type',
    'lastMonth': 'Last Month',
    'lastQuarter': 'Last Quarter',
    'lastYear': 'Last Year',
    'customRange': 'Custom Range',
    'totalServiceValue': 'Total Service Value',
    'totalExtraCosts': 'Total Extra Costs',
    'totalCost': 'Total Cost',
    'pendingBalance': 'Pending Balance',
    'operationAnalysis': 'Operation Analysis',
    'serviceValue': 'Service Value',
    'extraCosts': 'Extra Costs',
    'paymentStatus': 'Payment Status',
    'advance': 'Advance',
    'paymentSchedule': 'Payment Schedule',
    'paymentDescription': 'Payment Description',
    'dueDate': 'Due Date',
    'paid': 'Paid',
    'exchangeRate': 'Exchange Rate',
    'lastUpdated': 'Last Updated',
    'updateExchangeRate': 'Update exchange rate',
    'fuelCosts': 'Fuel Costs',
    'tollCosts': 'Toll Costs',
    'permitCosts': 'Permit Costs',
    'otherCosts': 'Other Costs',
    'advancePayment': 'Advance Payment',
    'finalPayment': 'Final Payment',
    'paymentDue': 'Payment Due',
    'paymentComplete': 'Payment Complete',
    'operationCosts': 'Operation Costs',
    'profitMargin': 'Profit Margin',
    'profitAnalysis': 'Profit Analysis',
    'costBreakdown': 'Cost Breakdown',
    'revenueAnalysis': 'Revenue Analysis',
    'paymentAnalysis': 'Payment Analysis',
    'operationMetrics': 'Operation Metrics',
    'serviceProviderCosts': 'Service Provider Costs',
    'operationalCosts': 'Operational Costs',
    'netProfit': 'Net Profit',
    'grossProfit': 'Gross Profit',
    'profitPercentage': 'Profit Percentage',
    'costPercentage': 'Cost Percentage',
    'revenuePercentage': 'Revenue Percentage',
    'valueUSD': 'Value (USD)',
    'valueCLP': 'Value (CLP)',
    'client': 'Client',
  },
  es: {
    // General
    'view': 'Ver',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'create': 'Crear',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'actions': 'Acciones',
    'status': 'Estado',
    'details': 'Detalles',
    'type': 'Tipo',
    'date': 'Fecha',
    'total': 'Total',
    'contact': 'Contacto',
    'description': 'Descripción',
    'name': 'Nombre',
    'email': 'Correo',
    'phone': 'Teléfono',
    'address': 'Dirección',
    'city': 'Ciudad',
    'country': 'País',
    'currency': 'Moneda',
    'amount': 'Monto',
    'download': 'Descargar',
    'upload': 'Subir',
    'complete': 'Completo',
    'incomplete': 'Incompleto',
    'required': 'Requerido',
    'optional': 'Opcional',
    'selectOption': 'Seleccione una opción',
    'carrierCost': 'Costo del Transportista',
    'saleValue': 'Valor de Venta',

    // Navigation
    'dashboard': 'Panel de Control',
    'operations': 'Operaciones',
    'documents': 'Documentos',
    'reports': 'Reportes',
    'settings': 'Configuración',
    'profile': 'Perfil',
    'logout': 'Cerrar Sesión',

    // Dashboard
    'totalTrips': 'Total de Viajes',
    'activeDocuments': 'Documentos Activos',
    'monthlyRevenue': 'Ingresos Mensuales',
    'pendingPayments': 'Pagos Pendientes',
    'pendingApproval': 'pendientes de aprobación',
    'increase': 'incremento',
    'tripVolume': 'Volumen de Viajes',
    'recentTrips': 'Viajes Recientes',
    'viewAll': 'Ver Todos',
    'tripId': 'ID de Viaje',
    'route': 'Ruta',
    'driver': 'Conductor',
    'value': 'Valor',
    'completed': 'Completado',
    'inTransit': 'En Tránsito',
    'pendingDocs': 'Docs Pendientes',
    'scheduled': 'Programado',

    // Operations
    'manageOperations': 'Gestionar y seguir todas las operaciones de transporte',
    'searchOperations': 'Buscar operaciones...',
    'allOperations': 'Todas las Operaciones',
    'newOperation': 'Nueva Operación',
    'operationNumber': 'Número de Operación',
    'operationType': 'Tipo de Operación',
    'international': 'Internacional',
    'national': 'Nacional',
    'inProgress': 'En Progreso',
    'pending': 'Pendiente',
    'startOperation': 'Iniciar Operación',
    'completeOperation': 'Completar Operación',
    'viewDetails': 'Ver Detalles',
    'requirements': 'Requisitos',
    'missingDocuments': 'Documentos Faltantes',
    'missingInsurance': 'Seguro Faltante',
    'missingServiceProvider': 'Proveedor de Servicio Faltante',
    'completeRequirementsFirst': 'Complete todos los requisitos antes de iniciar',
    'cargoInsurance': 'Seguro de Carga',
    'liabilityInsurance': 'Seguro de Responsabilidad',
    'assignServiceProvider': 'Asignar Proveedor de Servicio',
    'selectProvider': 'Seleccionar Proveedor',

    // Service Providers
    'serviceProviders': 'Proveedores de Servicio',
    'manageServiceProviders': 'Gestionar proveedores de servicio y sus operaciones',
    'newServiceProvider': 'Nuevo Proveedor de Servicio',
    'providerName': 'Nombre del Proveedor',
    'taxId': 'RUT/CUIT',
    'paymentTerms': 'Términos de Pago',
    'paymentTermsUSD': 'Términos de Pago (USD)',
    'paymentTermsCLP': 'Términos de Pago (CLP)',
    'serviceProvider': 'Proveedor de Servicio',
    'providerOperations': 'Operaciones del Proveedor',

    // Documents
    'documentRegistry': 'Registro de Documentos',
    'manageDocuments': 'Gestione todos sus documentos de transporte en un solo lugar',
    'addDocument': 'Agregar Documento',
    'registerNewDocument': 'Registrar Nuevo Documento',
    'documentType': 'Tipo de Documento',
    'documentDate': 'Fecha del Documento',
    'documentDescription': 'Descripción del Documento',
    'uploadDocument': 'Subir Documento',
    'searchDocuments': 'Buscar documentos...',
    'allDocuments': 'Todos los Documentos',
    'approved': 'Aprobado',
    'selectType': 'Seleccionar tipo',
    'selectOperation': 'Seleccionar operación',
    'uploadFile': 'Subir un archivo',
    'orDragAndDrop': 'o arrastrar y soltar',
    'uploadSuccess': 'Subida Exitosa',
    'documentRegistered': 'Documento Registrado',
    'registerDocument': 'Registrar Documento',
    'noDocumentsFound': 'No se encontraron documentos',
    'enterDescription': 'Ingrese descripción del documento',

    // Reports & Analytics
    'reports': 'Reportes y Análisis',
    'visualizeData': 'Visualice y analice sus datos de transporte',
    'exportToExcel': 'Exportar a Excel',
    'dateRange': 'Rango de Fechas',
    'reportType': 'Tipo de Reporte',
    'lastMonth': 'Último Mes',
    'lastQuarter': 'Último Trimestre',
    'lastYear': 'Último Año',
    'customRange': 'Rango Personalizado',
    'totalServiceValue': 'Valor Total del Servicio',
    'totalExtraCosts': 'Costos Extra Totales',
    'totalCost': 'Costo Total',
    'pendingBalance': 'Saldo Pendiente',
    'operationAnalysis': 'Análisis de Operaciones',
    'serviceValue': 'Valor del Servicio',
    'extraCosts': 'Costos Extra',
    'paymentStatus': 'Estado de Pago',
    'advance': 'Anticipo',
    'paymentSchedule': 'Calendario de Pagos',
    'paymentDescription': 'Descripción del Pago',
    'dueDate': 'Fecha de Vencimiento',
    'paid': 'Pagado',
    'exchangeRate': 'Tipo de Cambio',
    'lastUpdated': 'Última Actualización',
    'updateExchangeRate': 'Actualizar tipo de cambio',
    'fuelCosts': 'Costos de Combustible',
    'tollCosts': 'Costos de Peaje',
    'permitCosts': 'Costos de Permisos',
    'otherCosts': 'Otros Costos',
    'advancePayment': 'Pago Anticipado',
    'finalPayment': 'Pago Final',
    'paymentDue': 'Pago Pendiente',
    'paymentComplete': 'Pago Completado',
    'operationCosts': 'Costos de Operación',
    'profitMargin': 'Margen de Ganancia',
    'profitAnalysis': 'Análisis de Ganancias',
    'costBreakdown': 'Desglose de Costos',
    'revenueAnalysis': 'Análisis de Ingresos',
    'paymentAnalysis': 'Análisis de Pagos',
    'operationMetrics': 'Métricas de Operación',
    'serviceProviderCosts': 'Costos del Proveedor',
    'operationalCosts': 'Costos Operacionales',
    'netProfit': 'Ganancia Neta',
    'grossProfit': 'Ganancia Bruta',
    'profitPercentage': 'Porcentaje de Ganancia',
    'costPercentage': 'Porcentaje de Costo',
    'revenuePercentage': 'Porcentaje de Ingreso',
    'valueUSD': 'Valor (USD)',
    'valueCLP': 'Valor (CLP)',
    'client': 'Cliente',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};